### ISSUE TITLE
Add other package reference in the paper

### ISSUE THREAD

**Issue by Marie-PerrotDockes** [PhilBoileau/cvCovEst#50]
Can you add in the paper a few words on  other packages that already exists to compare covariance matrix estimation ? 
For instance : CovTools provides different ways of estimating covariance matrix  and tests to compare them to a given matrix or evolqg which also provides many estimations techniques for covariance matrices. 

This two packages are not doing exactly the same thing that you are doing but I think  your paper lack a bit of comparison to existing package.

**Comment by PhilBoileau** [comment]
Thank you for pointing out this issue! We now cite a few R packages that implement different classes of covariance matrix estimators. While we don't directly compare their functionalities to our package, we state in the third paragraph of the Statement of Need that no other method/package is capable of making asymptotically optimal covariance matrix estimator selections from among a wide range of estimator classes. We hope that this addresses your concern. If you think that we should cite other packages elsewhere in the text, please feel free to make a suggestion.

**Comment by Marie-PerrotDockes** [comment]
Perfect thank you !
