### ISSUE TITLE
Request for Shrinkage Estimators for Spiked Covariance Models

### ISSUE THREAD

**Issue by bcollica** [PhilBoileau/cvCovEst#63]
There has been a request to implement some of the shrinkage estimators described by [Donoho, Gavish, and Johnstone](https://arxiv.org/pdf/1311.0851.pdf).  The paper presents analytical formulas for 18 different "optimal" estimators depending on the loss function.  The request was for the estimators based on Stein and Operator loss, but it should be fairly straight forward to create a single wrapper estimator which can house one or more of these shrinkage functions with the Frobenius norm being the default so it can fit within the current CV framework.

**Comment by PhilBoileau** [comment]
I've implemented three standalone shrinkage estimators for Gaussian spiked covariance models in #64. They are `spikedOpertatorShrinkEst()`, `spikedFrobeniusShrinkEst()` and `spikedSteinShrinkEst()`. I'll submit this update to CRAN later today.

@bcollica, please let me know if your collaborators would be interested in other shrinkage estimators. It won't take much effort to implement them now that all the required functionality for these estimators has been included in the package. I'm also happy to discuss with them directly if they have any questions or need any help.
